
<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


### 1. Todas las empresas cuyo nombre sea 'Babelgum'. Recupera solo su campo `name`.

In [91]:
import pandas as pd
import numpy as np
from datetime import datetime
import pymongo

In [92]:
cliente = pymongo.MongoClient()
print(cliente)
cliente.list_database_names()

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

['Airbnb', 'Companies', 'admin', 'config', 'local']

In [93]:
base_de_datos= cliente['Companies']
base_de_datos.list_collection_names()
base_de_datos

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'Companies')

In [94]:
coleccion = base_de_datos['Companies']
coleccion

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'Companies'), 'Companies')

In [95]:
df_name =  pd.DataFrame(coleccion.find({'name': 'Babelgum'},{'name':1, '_id':0}))

In [96]:
df_name

       name
0  Babelgum

### 2. Todas las empresas que tienen más de 5000 empleados. Limita la búsqueda a 20 empresas y ordénalas por **número de empleados**.

In [97]:
find_eq_df = pd.DataFrame(coleccion.find({'number_of_employees': {"$gt":5000}}))
find_eq_df.head(20)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299,2004.0,2.0,1.0,None,None,None,,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,Thu Nov 21 19:40:55 UTC 2013,<p>Facebook is the world&#8217;s largest socia...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Facebook Platform', 'permalink': 'f...","[{'is_past': False, 'title': 'Founder and CEO,...","[{'competitor': {'name': 'MySpace', 'permalink...","[{'title': '', 'is_past': False, 'provider': {...",$2.43B,"[{'id': 2, 'round_code': 'angel', 'source_url'...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]
1,52cdef7c4bab8bd675297d9b,eBay,ebay,http://www.crunchbase.com/company/ebay,http://ebay.com,,,eBay,web,15000,1995.0,9.0,1.0,None,None,None,None,"auction, bid, search, market",,,,Online Marketplace,Wed Jun 06 13:03:13 UTC 2007,Tue Sep 10 03:38:03 UTC 2013,"<p>Founded in 1995 in San Jose, CA, eBay conne...","{'available_sizes': [[[150, 62], 'assets/image...","[{'name': 'eBay Marketplace', 'permalink': 'eb...","[{'is_past': False, 'title': 'Founder', 'perso...","[{'competitor': {'name': 'Taobao', 'permalink'...","[{'title': 'Public Relations', 'is_past': Fals...",$6.7M,"[{'id': 24534, 'round_code': 'unattributed', '...","[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': 1500000000, 'price_currency_...","[{'description': 'Headquarters', 'address1': '...","[{'id': 7107, 'description': 'eBay Q2 Revenue ...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<iframe width=""370"" height=""3...","[{'available_sizes': [[[150, 71], 'assets/imag...",[],[]
2,52cdef7c4bab8bd675297da2,Cisco,cisco,http://www.crunchbase.com/company/cisco,http://www.cisco.com,http://blogs.cisco.com,,CiscoSystems,network_hosting,63000,1984.0,NaN,NaN,None,None,None,,networking,,,(408) 526-4000,,Sat Jun 09 14:33:35 UTC 2007,Fri Dec 13 03:59:09 UTC 2013,"<p>Cisco designs and sells hardware, software,...","{'available_sizes': [[[110, 73], 'assets/image...",[],"[{'is_past': False, 'title': 'SVP, Office of t...",[],"[{'title': '', 'is_past': False, 'provider': {...",$2.5M,"[{'id': 2232, 'round_code': 'a', 'source_url':...","[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': 215000000, 'price_currency_c...","[{'description': 'Headquarters', 'address1': '...","[{'id': 10474, 'description': 'Cisco To Acquir...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 92], 'assets/imag...",[{'external_url': 'http://mashpedia.com/cisco'...,[]
3,52cdef7c4bab8bd675297da3,Yahoo!,yahoo,http://www.crunchbase.com/company/yahoo,http://www.yahoo.com,http://ycorpblog.com/,http://ycorpblog.com/feed/,Yahoo,web,13600,1994.0,1.0,1.0,None,None,None,None,"search, portal, webmail, photos",Yahoo,,(408) 349-3300,News and On-line directory,Sun Nov 04 01:48:15 UTC 2007,Mon Dec 09 04:26:08 UTC 2013,<p>Yahoo was founded in 1994 by Stanford Ph.D....,"{'available_sizes': [[[142, 37], 'assets/image...","[{'name': 'Yahoo.com', 'permalink': 'yahoo-com...","[{'is_past': False, 'title': 'CEO, President',...","[{'competitor': {'name': 'Google', 'permalink'...","[{'title': '', 'is_past': False, 'provider': {...",$6.8M,"[{'id': 24531, 'round_code': 'a', 'source_url'...","[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': 1000000000, 'price_currency_...","[{'description': None, 'address1': '701 First ...","[{'id': 347, 'description': 'CBS and Yahoo in ...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 132], 'assets/ima...",[{'external_url': 'http://onlinepersonalswatch...,[]
4,52cdef7c4bab8bd675297dba,Google,google,http://www.crunchbase.com/company/google,http://google.com,http://googleblog.blogspot.com,http://googleblog.blogspot.com/feeds/posts/def...,google,search,28000,1998.0,9.0,7.0,None,None,None,None,"search, gmail, blogger, find, information, you...",Google,google@google.com,650.253.0000,,Sat Jun 30 22:18:12 UTC 2007,Mon Jan 06 04:52:54 UTC 2014,<p>Google provides search and advertising serv...,"{'available_sizes': [[[150, 51], 'assets/image...","[{'name': 'Gmail', 'permalink': 'gmail'}, {'na...","[{'is_past': False, 'title': 'CEO of Google Co...","[{'competitor': {'name': 'Technorati', 'permal...","[{'title': 'Public Relations (APAC)', 'is_past...",$555M,"[{'id': 380, 'round_code': 'angel', 'source_ur...","[{'funding_round': {'round_code': 'a', 'source...",None,"[{'price_amount': 60000000, 'price_currency_co...","[{'description': 'Google Headquarters', 'addre...","[{'id': 3, 'description': 'More than 4 Billion...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...",[],[],"[{'partner_name': 'AngelList', 'homepage_url':..."
5,52cdef7c4bab8bd675297dc4,Intel,intel,http://www.crunchbase.com/company/intel,http://www.intel.com,,,intel,hardware,86300,1968.0,NaN,NaN,None,None,None,None,None,,,,Microprocessor Developer,Tue Feb 05 22:28:14 UTC 2008,Mon Nov 11 04:29:21 UTC 2013,<p>Intel is best known for producing the micro...,"{'available_sizes': [[[150, 99], 'assets/image...",[],"[{'is_past': False, 'title': 'President & CEO'...","[{'competitor': {'name': 'PA Semi', 'permalink...","[{'title': 'Hosting', 'is_past': False, 'provi...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': 884000000, 'price_currency_c...","[{'description': 'Robert Noyce Building', 'add...","[{'id': 3992, 'description': 'Intel announces ...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 92], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Intel'...,[]
6,52cdef7c4bab8bd675297e49,Nintendo,nintendo,http://www.crunchbase.com/company/nintendo,http://nintendo.com,,,NintendoAmerica,games_video,5080,1889.0,9.0,23.0,None,None,None,None,"games, console",,noalegal@noa.nintendo.com,1-800-255-3700,,Sat Dec 22 13:27:00 UTC 2007,Thu Sep 05 12:41:16 UTC 2013,"<p>Nintendo, a technology company widely known...","{'available_sizes': [[[150, 41], 'assets/image...","[{'name': 'Wii', 'permalink': 'wii'}]","[{'is_past': False, 'title': 'President', 'per...",[],[],$0,[],[],None,[],"[{'description': None, 'address1': None, 'addr...","[{'id': 17591, 'description': '3D For Everyone...",None,[],[],[],[]
7,52cdef7c4bab8bd675297e5d,Adobe Systems,adobe-systems,http://www.crunchbase.com/company/adobe-systems,http://www.adobe.com,http://blogs.adobe.com/,http://blogs.adobe.com/index.xml,Adobe,software,7173,1982.0,12.0,NaN,None,None,None,,"adobe, flash, illustrator, creative, photoshop...",,,408-536-6000,,Thu Aug 09 01:22:40 UTC 2007,Fri Aug 09 22:20:08 UTC 2013,<p>Adobe Systems Incorporated is a diversified...,"{'available_sizes': [[[109, 150], 'assets/imag...","[{'name': 'photoshop.com', 'permalink': 'photo...","[{'is_past': False, 'title': 'Co-founder, Co-C...","[{'competitor': {'name': 'Apple', 'permalink':...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 3400000000, 'price_currency_...","[{'description': '', 'address1': '', 'address2...","[{'id': 6, 'description': 'Adobe announced new...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...",[{'external_url': 'http://www.crunchbase.com/f...,[]
8,52cdef7c4bab8bd675297e6f,Sony,sony,http://www.crunchbase.com/company/sony,http://www.sony.com,http://blog.sony.com/,http://blog.sony.com/,Sony,hardware,180500,1946.0,NaN,NaN,None,None,None,None,None,,,858-942-2729,Consumer Electronics,Fri Jul 27 12:47:37 UTC 2007,Tue Dec 10 19:09:15 UTC 2013,<p>Sony is one of the leading manufacturers of...,"{'available_sizes': [[[117, 49], 'assets/image...","[{'name': 'PlayStation 3', 'permalink': 'plays...","[{'is_past': False, 'title': 'President and CE...","[{'competitor': {'name': 'Apple', 'permalink':...","[{'title': 'Public Relations (APAC)', 'is_past...",$0,[],[],None,"[{'price_amount': 260000000, 'price_currency_c...","[{'description': 'HQ', 'address1': '16530 Via ...","[{'id': 18773, 'description': 'Sony Will Buy O...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[{'external_url': 'http://www.entechgadget.com...,[]
9,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000,1998.0,12.0,1.0,None,None,None,None,"moneytransfer, crunchbase, ecommerce, paypal, ...",,,207-619-2873,Internet payment service,Wed Aug 01 09:16:46 UTC 2007,Fri Dec 20 04:43:53 UTC 2013,<p>PayPal is an online payments and money tran...,"{'available_sizes': [[[150, 51], 'assets/image...","[{'name': 'PayPal Here', 'permalink': 'paypal-...","[{'is_past': False, 'title': 'Vice President, ...","[{'competitor': {'name': 'KushCash', 'permalin...","[{'title': 'Public Relations', 'is_past': True...",$197M,"[{'id': 284, 'round_code': 'd', 'source_url': ...","[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]
10,52cdef7c4bab8bd675297e8e,The Walt Disney Company,the-walt-disney-company,http://www.crunchbase.com/company/the-walt-dis...,http://thewaltdisneycompany.com,http://thewaltdisneycompany.com/blog,,DisneyPost,games_video,25000,1923.0,10.0,16.0,None,None,None,,"disney, media, entertainment, movies",Disney,,818-560-1000,,Thu Aug 02 09:08:05 UTC 2007,Mon Nov 18 17:26:25 UTC 2013,<p>The Walt Disney Company is a media and ente...,"{'available_sizes': [[[150, 78], 'assets/image...",[],"[{'is_past': False, 'title': 'Chairman & CEO',...",[],[],$0,[],"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 350000000, 'price_currency_c...","[{'description': None, 'address1': '500 S. Bue...","[{'id': 6970, 'description': 'Disney About To ...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 92], 'assets/imag...",[{'external_url': 'http://jobs.disney.corp.go....,[]
11,52cdef7c4bab8bd675297e96,AOL,aol,http://www.crunchbase.com/company/aol,http://www.aol.com,http://blog.aol.com/,http://feeds.feedburner.com/AolBlog?format=xml,aol,web,8000,1985.0,5.0,24.0,None,None,None,,"american-on-line, america-online","America Online, America on-line",,+1-703-265-1000,,Fri Aug 03 06:26:04 UTC 2007,Fri Nov 29 21:51:48 UTC 2013,<p>AOL is a global advertising-supported Web c...,"{'available_sizes': [[[150, 84], 'assets/image...","[{'name': 'Xdrive', 'permalink': 'xdrive'}, {'...","[{'is_past': False, 'title': 'CEO, Chairman', ...","[{'competitor': {'name': 'MySpace', 'permalink...",[],$1B,"[{'id': 3548, 'round_code': 'post_ipo_equity',...","[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 40000000, 'price_currency_co...","[{'description': 'HQ', 'address1': '770 Broadw...","[{'id': 2689, 'description': 'AOL relauches, c...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 91], 'assets/imag...","[{'external_url': 'http://mashpedia.com/AOL', ...",[]
12,52cdef7c4bab8bd675297ea4,Webkinz,webkinz,http://www.crunchbase.com/company/webkinz,http://www.webkinz.com,http://www.webkinz.com,http://piczo.com,webkinz,web,8657,2005.0,4.0,25.0,None,None,None,,"webkinz, virtualworld, virtualpets, crunchbase...",,support@webkinz.com,4164682415,,Mon Aug 06 09:45:48 UTC 2007,Thu Mar 21 13:16:34 UTC 2013,<p>Webkinz is a virtual world for kids owned b...,"{'available_sizes': [[[150, 96], 'assets/image...","[{'name': 'Webkinz', 'permalink': 'webkinz'}]","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Neopets', 'permalink...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],[],None,[],"[{'description': None, 'address1': 'One Pearce...",[],None,[],[],"[{'external_url': 'http://webkinz-tips.com', '...",[]
13,52cdef7c4bab8bd675297ee9,Sun Microsystems,sun-microsystems,http://www.crunchbase.com/company/sun-microsys...,http://www.sun.com,,,sunmicrosystems,enterprise,33350,1982.0,2.0,NaN,None,None,None,None,"vendor, computer, hardware, software",Sun,,1-800-786-0404,Computer Hardware and Software Provider,Sat Aug 18 08:52:54 UTC 2007,Thu Mar 14 14:41:26 UTC 2013,<p>Sun Microsystems is a multinational vendor ...,"{'available_sizes': [[[150, 71], 'assets/image...","[{'name': 'Sun Glassfish', 'permalink': 'sun-g...","[{'is_past': False, 'title': 'Chief Executive ...","[{'competitor': {'name': 'Adobe Systems', 'per...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 7400000000, 'price_currency_c...","[{'price_amount': 1000000000, 'price_currency_...","[{'description': None, 'address1': '4150 Netwo...","[{'id': 196, 'description': 'NBC selects Sun t...",None,"[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 92], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Sun_Mi...,[]
14,52cdef7c4bab8bd675297fc2,Nokia,nokia,http://www.crunchbase.com/company/nokia,http://nokia.com,,,nokia,mobile,125000,1865.0,NaN,NaN,None,None,None,,"mobile, phone",,miremadalavi@gmail.com,+989126715133,Mobile Devices,Tue Sep 04 12:08:11 UTC 2007,Tue Sep 17 12:49:12 UTC 2013,<p>NOKIA is a Finnish multinational communicat...,"{'available_sizes': [[[120, 50], 'assets/image...","[{'name': 'Nokia Chat', 'permalink': 'nokia-ch...","[{'is_past': False, 'title': 'Chairman of the ...","[{'competitor': {'name': 'Apple', 'permalink':...","[{'title': 'Marketing', 'is_past': False, 'pro...",$0,[],"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 96800000, 'price_currency_co...","[{'description': 'headquarter', 'address1': 'K...","[{'id': 9161, 'description': 'Nokia, AT&T Putt...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 131], 'assets/ima...",[{'external_url': 'http://en.wikipedia.org/wik...,[]
15,52cdef7c4bab8bd675297fcb,Rakuten,rakuten,http://www.crunchbase.com/company/rakuten,http://global.rakuten.com/corp,,,RakutenGlobal,web,10000,1997.0,2.0,7.0,None,None,None,None,"ecommerce, japan, global, internet-services, p...",bitWallet,,+81-3-6387-0555,Online mall operator,Tue Sep 04 10:54:37 UTC 2007,Wed Oct 16 08:08:23 UTC 2013,"<p>Rakuten, Inc. (JASDAQ: 4755), is one of the...","{'available_sizes': [[[150, 29], 'assets/image...",[],"[{'is_past': False, 'title': 'Chairman & CEO',...","[{'competitor': {'name': 'Amazon', 'permalink'...",[],$42.4M,"[{'id': 52008, 'round_code': 'unattributed', '...",[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': 425000000, 'price_currency_c...","[{'description': 'Headquarter', 'address1': 'R...","[{'id': 7034, 'description': 'RS Empowerment a...",None,[],"[{'available_sizes': [[[150, 111], 'assets/ima...",[{'external_url': 'http://www.brightwire.com/c...,[]
16,52cdef7c4bab8bd67529809d,Microsoft,microsoft,http://www.crunchbase.com/company/microsoft,http://www.microsoft.com,,,Microsoft,software,90000,1974.0,4.0,4.0,None,None,None,,"bill-gates, xbox, windows, vista, xp",msn,,,,Sat Nov 03 12:45:12 UTC 2007,Fri Dec 27 17:02:28 UTC 2013,"<p>Microsoft, founded in 1975 by Bill Gates an...","{'available_sizes': [[[150, 32], 'assets/image...","[{'name': 'Windows Live FolderShare', 'permali...","[{'is_past': False, 'title': 'Founder, Chairma...","[{'competitor': {'name': 'Mesa Dynamics', 'per...","[{'title': 'Web Development, Social Markeitng'...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': 50000000, 'price_currency_co...","[{'description': 'World Headquarters', 'addres...","[{'id': 9073, 'description': 'Microsoft Actual...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<div style=""width:430px;""><di...","[{'available_sizes': [[[99, 150], 'assets/imag...",[],[]
17,52cdef7c4bab8bd675298189,Apple,apple,http://www.crunchbase.com/company/apple,http://www.apple.com,,,ebelow,hardware,80000,1976.0,4.0,1.0,None,None,None,None,"apple, computers, ipods, iphones, digitalmusic",,,1-800-MY-APPLE,,Sat Dec 22 04:28:53 UTC 2007,Fri Dec 27 22:47:38 UTC 2013,"<p>Apple Inc., formerly Apple Computer, Inc., ...","{'available_sizes': [[[120, 150], 'assets/imag...","[{'name': 'iPhone', 'permalink': 'iphone'}, {'...","[{'is_past': False, 'title': 'CEO & Board Dire...","[{'competitor': {'name': 'Microsoft', 'permali...","[{'title': 'Legal', 'is_past': False, 'provide...",$0,[],[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': 278000000, 'price_currency_c...","[{'description': None, 'address1': '1 Infinite...","[{'id': 782, 'description': 'Apple Sells 6.9 M...","{'valuation_amount': None, 'valuation_currency...",[],[],[{'external_url': 'http://thcx.org/tech-news/i...,[]
18,52cdef7c4bab8bd6752981b5,NetApp,netapp,http://www.crunchbase.com/company/netapp,http://netapp.com,http://blogs.netapp.com/dave/,http://blogs.netapp.com/dave/index.rdf,netapp,software,8000,1992.0,NaN,NaN,None,None,None,None,,network appliance,,,,Fri Jan 04 07:41:24 UTC 2008,Mon Dec 10 02:19:29 UTC 2012,<p>NetApp creates storage and data management ...,"{'available_sizes': [[[88, 94], 'assets/images...",[],"[{'is_past': False, 'title': 'Executive Chairm...","[{'competitor': {'name': 'PernixData', 'permal...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': 120000000, 'price_currency_c...","[{'description': None, 'address1': None, 'addr...","[{'id': 12113, 'description': 'The price paid ...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 94], 'assets/imag...",[],[]

### 3. Todas las empresas fundadas entre 2000 y 2005, incluyendo ambos años. Recupera solo los campos `name` y `founded_year`.

In [98]:
cond_precio = {"founded_year": {"$gte": 2000}}
cond_camas = {"founded_year": {'$lte':2005}}

# realizamos la query
find_and = pd.DataFrame(coleccion.find({"$and": [cond_precio, cond_camas]},{'name':1, '_id':0,'founded_year':1}))
find_and.head(2)

       name  founded_year
0  Wetpaint          2005
1      Zoho          2005

### 4. Todas las empresas que tuvieron una valoración de más de 100.000.000 y que fueron fundadas antes de 2010. Recupera solo los campos `name` e `ipo`.

In [99]:
find_eq_df.head(0)

Empty DataFrame
Columns: [_id, name, permalink, crunchbase_url, homepage_url, blog_url, blog_feed_url, twitter_username, category_code, number_of_employees, founded_year, founded_month, founded_day, deadpooled_year, deadpooled_month, deadpooled_day, deadpooled_url, tag_list, alias_list, email_address, phone_number, description, created_at, updated_at, overview, image, products, relationships, competitions, providerships, total_money_raised, funding_rounds, investments, acquisition, acquisitions, offices, milestones, ipo, video_embeds, screenshots, external_links, partners]
Index: []

In [100]:
find_eq_df['ipo'][0]

{'valuation_amount': 104000000000,
 'valuation_currency_code': 'USD',
 'pub_year': 2012,
 'pub_month': 5,
 'pub_day': 18,
 'stock_symbol': 'NASDAQ:FB'}

In [124]:
cond_v = {"ipo.valuation_amount": {"$gte": 100000000}}
con = {"founded_year": {'$lte':2010}}

# realizamos la query
find_and1 = pd.DataFrame(coleccion.find({"$and": [cond_v, con]},{'name':1, 'ipo.valuation_amount':1,'_id':0}))
find_and1.head(10)

             name                                 ipo
0        Facebook  {'valuation_amount': 104000000000}
1         Twitter   {'valuation_amount': 18100000000}
2            Yelp    {'valuation_amount': 1300000000}
3        LinkedIn    {'valuation_amount': 9310000000}
4          Amazon  {'valuation_amount': 100000000000}
5      Brightcove     {'valuation_amount': 290000000}
6     KIT digital     {'valuation_amount': 235000000}
7         Nielsen    {'valuation_amount': 1600000000}
8       OpenTable    {'valuation_amount': 1050000000}
9  ChannelAdvisor     {'valuation_amount': 287000000}

### 5. Todas las empresas que tienen menos de 1000 empleados y que fueron fundadas antes de 2005. Ordénalas por el número de empleados y limita la búsqueda a 10 empresas.

In [152]:
cond_2 = {"founded_year": {"$lte":2005 }}
con1 = {"number_of_employees": {'$lte':1000}}
 

# realizamos la query
find_and2 = pd.DataFrame(coleccion.find({"$and": [cond_v, con]},{'name':1, 'number_of_employees':1,'founded_year':1,'_id':0}))
find_and_5 = pd.DataFrame(coleccion.find({"$and": [cond_v, con]}).limit(10).sort({"number_of_employees":-1}))                                     
find_and_5

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd675299d5d,Groupon,groupon,http://www.crunchbase.com/company/groupon,http://www.groupon.com,http://www.groupon.com/blog/,feed://feeds2.feedburner.com/grouponblog,groupon,web,10000,2008,11.0,11.0,None,None,None,None,"woot, deal-of-the-day, collective-action, the-...",thepoint,mail@groupon.com,7707886505,Local Daily Deals,Tue Sep 23 22:07:32 UTC 2008,Mon Dec 02 03:18:41 UTC 2013,<p>Groupon (NASDAQ: GRPN) is a global leader i...,"{'available_sizes': [[[150, 66], 'assets/image...",[],"[{'is_past': False, 'title': 'CEO's PA', 'pers...","[{'competitor': {'name': 'Woot', 'permalink': ...","[{'title': 'legal', 'is_past': False, 'provide...",$1.15B,"[{'id': 9831, 'round_code': 'a', 'source_url':...",[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ', 'address1': '600 W. Chi...","[{'id': 4396, 'description': 'Groupon Makes A ...","{'valuation_amount': 12800000000, 'valuation_c...","[{'embed_code': '<script src=""http://www.buzzs...","[{'available_sizes': [[[150, 97], 'assets/imag...",[{'external_url': 'http://web20show.com/2009/1...,[]
1,52cdef7c4bab8bd675298760,Baidu,baidu,http://www.crunchbase.com/company/baidu,http://www.baidu.com,,,baidu_,search,6000,1999,10.0,11.0,None,None,None,None,search,,ir@baidu.com,86 10 8262 1188,,Mon Apr 07 23:06:27 UTC 2008,Mon Jan 06 10:56:31 UTC 2014,<p>It is the largest Chinese website and Chine...,"{'available_sizes': [[[150, 71], 'assets/image...","[{'name': 'Baidu Space', 'permalink': 'baidu-s...","[{'is_past': False, 'title': 'Co-founder', 'pe...","[{'competitor': {'name': 'Google', 'permalink'...",[],$161M,"[{'id': 1979, 'round_code': 'c', 'source_url':...",[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': None, 'address1': 'No. 58 Nor...","[{'id': 3434, 'description': 'Banners Broker M...","{'valuation_amount': 4000000000, 'valuation_cu...","[{'embed_code': '<object width=""425"" height=""3...","[{'available_sizes': [[[150, 74], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Baidu'...,"[{'partner_name': 'CTQuan', 'homepage_url': 'h..."
2,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299,2004,2.0,1.0,None,None,None,,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,Thu Nov 21 19:40:55 UTC 2013,<p>Facebook is the world&#8217;s largest socia...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Facebook Platform', 'permalink': 'f...","[{'is_past': False, 'title': 'Founder and CEO,...","[{'competitor': {'name': 'MySpace', 'permalink...","[{'title': '', 'is_past': False, 'provider': {...",$2.43B,"[{'id': 2, 'round_code': 'angel', 'source_url'...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]
3,52cdef7c4bab8bd675297e0c,LinkedIn,linkedin,http://www.crunchbase.com/company/linkedin,http://linkedin.com,http://blog.linkedin.com,,linkedin,social,4800,2003,5.0,NaN,None,None,None,None,"social, resume, networking, manufacturers",,,650 687 3560,Professional Social Networking,Tue Jul 17 04:21:55 UTC 2007,Fri Dec 27 16:02:27 UTC 2013,"<p>Founded in 2003, LinkedIn connects the worl...","{'available_sizes': [[[150, 68], 'assets/image...","[{'name': 'LinkedIn', 'permalink': 'linkedin'}...","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Visible Path', 'perm...","[{'title': 'Legal', 'is_past': False, 'provide...",$200M,"[{'id': 152, 'round_code': 'a', 'source_url': ...",[],None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ', 'address1': '2029 Stier...","[{'id': 10120, 'description': 'LinkedIn CEO Je...","{'valuation_amount': 9310000000, 'valuation_cu...",[],"[{'available_sizes': [[[150, 75], 'assets/imag...",[{'external_url': 'http://www.linkedin.com/in/...,[]
4,52cdef7c4bab8bd67529823b,Salesforce,salesforce,http://www.crunchbase.com/company/salesforce,http://www.salesforce.com,http://blogs.salesforce.com,http://blogs.salesforce.com/blogs/atom.xml,salesforce,enterprise,3500,1999,NaN,NaN,None,None,None,,"cloud, enterprise, oracle",,info@salesforce.com,415-901-7000,Enterprise Cloud Computing,Mon Feb 11 21:21:16 UTC 2008,Wed Dec 18 01:46:25 UTC 2013,<p>Salesforce is an enterprise cloud computing...,"{'available_sizes': [[[150, 150], 'assets/imag...","[{'name': 'Sales Cloud', 'permalink': 'salesfo...","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Senokian', 'permalin...","[{'title': '', 'is_past': False, 'provider': {...",$99.9M,"[{'id': 2041, 'round_code': 'seed', 'source_ur...","[{'funding_round': {'round_code': 'a', 'source...",None,"[{'price_amount': 31500000, 'price_currency_co...","[{'description': 'HQ', 'address1': 'The Landma...","[{'id': 28, 'description': 'Salesforce release...","{'valuation_amount': 110000000, 'valuation_cur...","[{'embed_code': '<object width=""430"" height=""2...","[{'available_sizes': [[[150, 72], 'assets/imag...",[{'external_url': 'http://www.youtube.com/user...,[]
5,52cdef7c4bab8bd675297d94,Twitter,twitter,http://www.crunchbase.com/company/twitter,http://twitter.com,http://twitter.com/blog,http://feeds.feedburner.com/TwitterBlog,twitter,social,1300,2006,3.0,21.0,None,None,None,,"text, messaging, social, community, twitter, t...",,press@twitter.com,,Real time communication platform,Fri Jun 01 08:42:34 UTC 2007,Sat Dec 07 16:07:56 UTC 2013,"<p>Created in 2006, Twitter is a global real-t...","{'available_sizes': [[[150, 150], 'assets/imag...","[{'name': 'Twitter Blocks', 'permalink': 'twit...","[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Digg', 'permalink': ...","[{'title': 'Hosting', 'is_past': True, 'provid...",$1.16B,"[{'id': 261, 'round_code': 'a', 'source_url': ...",[],None,"[{'price_amount': 15000000, 'price_currency_co...","[{'description': '', 'address1': '1355 Market ...","[{'id': 1, 'description': 'Survives iPhone 3G ...","{'valuation_amount': 18100000000, 'valuation_c...","[{'embed_code': '<iframe width=""430"" height=""2...","[{'available_sizes': [[[150, 74], 'assets/imag...",[{'external_url': 'http://sec.gov/cgi-bin/brow...,[]
6,52cdef7d4bab8bd6752989f2,Telenav,telenav,http://www.crunchbase.com/company/telenav,http://www.telenav.com,http://blog.telenav.com/,http://feeds.feedburner.com/telenav/navigating...,telenav,mobile,1000,1999,9.0,9.0,None,None,None,None,"mobile, wireless, location-based-services, lbs...",,media@telenav.com,408-245-3800,Mobile location-based services (LBS),Wed May 07 23:57:24 UTC 2008,Fri Jul 12 13:16:23 UTC 2013,<p>Telenav is a provider of consumer location-...,"{'available_sizes': [[[150, 42], 'assets/image...","[{'name': 'TeleNav GPS Navigator', 'permalink'...","[{'is_past': False, 'title': 'VP of R&D and C-...","[{'competitor': {'name': 'Garmin', 'permalink'...","[{'title': 'Investor Relations', 'is_past': Fa...",$33.6M,"[{'id': 16379, 'round_code': 'e', 'source_url'...","[{'funding_round': {'round_code': 'angel', 'so...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'TeleNav US - Headquarters', ...","[{'id': 6140, 'description': 'TeleNav launches...","{'valuation_amount': 337000000, 'valuation_cur...","[{'embed_code': '<object width=""480"" height=""2...","[{'available_sizes': [[[150, 72], 'assets/imag...",[],[]
7,52cdef7e4bab8bd67529b3bd,Cornerstone OnDemand,cornerstone-ondemand,http://www.crunchbase.com/company/cornerstone-...,http://www.cornerstoneondemand.com,http://www.cornerstoneondemand.com/blog,http://www.cornerstoneondemand.com/blog,cornerstoneinc,software,881,1999,11.0,NaN,None,None,None,None,"talent-management, enterprise, learning-manage...",,info@cornerstoneondemand.com,1 (888) 365-2763,integrated talent management software,Sun Mar 15 14:45:14 UTC 2009,Tue Nov 05 09:46:58 UTC 2013,<p>Cornerstone OnDemand is a leading global pr...,"{'available_sizes': [[[150, 36], 'assets/image...",[],"[{'is_past': False, 'title': 'Founder & CEO', ...","[{'competitor': {'name': 'SuccessFactors', 'pe...",[],$44.7M,"[{'id': 5331, 'round_code': 'e', 'source_url':...",[],None,[],"[{'description': 'Headquarters', 'address1': '...","[{'id': 7141, 'description': 'Announced hire o...","{'valuation_amount': 900000000, 'valuation_cur...",[],[],[],[]
8,52cdef7c4bab8bd675297de0,Yelp,yelp,http://www.crunchbase.com/company/yelp,http://yelp.com,http://officialblog.yelp.com/,http://naturallylindy.com,Yelp,search,800,2004,7.0,1.0,None,None,None,None,"localsearch, localreviews, reviews, avriette",,,,Local search and review site,Tue Jul 10 06:21:37 UTC 2007,Wed Nov 13 09:32:29 UTC 2013,<p>Yelp (NYSE: YELP) connects people with grea...,"{'available_sizes': [[[150, 62], 'assets/image...",[],"[{'is_past': False, 'title': 'co-founder', 'pe...","[{'competitor': {'name': 'Insider Pages', 'per...","[{'title': '', 'is_past': False, 'provider': {...",$90M,"[{'id': 95, 'round_code': 'c', 'source_url': '...",[],None,"[{'price_amount': 50000000, 'price_currency_co...","[{'description': '', 'address1': '706 Mission ...","[{'id': 5336, 'description': 'Yelp Launches in...","{'valuation_amount': 1300000000, 'valuation_cu...",[],"[{'available_sizes': [[[150, 75], 'assets/imag...",[{'external_url': 'http://en.wikipedia.org/wik...,[]
9,52cdef7e4bab8bd67529a8b4,GREE,gree,http://www.crunchbase.com/company/gree,http://www.gree-corp.com,,,gree_corp,games_video,700,2004,12.0,7.0,None,None,None,None,"mobile-web, japan, tokyo, social-network, mobi...",None,inquiry@gree-corp.com,,"Internet media business,SNS, free game",Sat Dec 20 16:42:57 UTC 2008,Tue Jan 01 21:37:04 UTC 2013,<p>GREE provides Japan&#8217;s leading mobile ...,"{'available_sizes': [[[150, 61], 'assets/image...",[],"[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Mobage-town', 'perma...",[],¥464M,"[{'id': 18872, 'round_code': 'unattributed', '...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': 104000000, 'price_currency_c...","[{'description': 'Headquarters', 'address1': '...","[{'id': 1021, 'description': 'IPO', 'stoned_ye...","{'valuation_amount': 108960000000, 'valuation_...",[],"[{'available_sizes': [[[133, 150], 'assets/ima...",[],[]

### 6. Todas las empresas que no incluyen el campo `partners`.

In [166]:
partners = pd.DataFrame(coleccion.find({'partners': {'$exists': False}}))
partners

Empty DataFrame
Columns: []
Index: []

### 7. Todas las empresas que tienen un valor nulo en el campo `category_code`.

In [170]:
valores_nulos= pd.DataFrame(coleccion.find({'category_code': {'$exists': False}}))
valores_nulos.describe

<bound method NDFrame.describe of Empty DataFrame
Columns: []
Index: []>

### 8. Todas las empresas que tienen al menos 100 empleados pero menos de 1000. Recupera solo los campos `name` y `number of employees`.

In [173]:
cond1 = {"number_of_employees": {"$gte": 100}}
cond2 = {"number_of_employees": {"$lt": 1000}}

Name_number = pd.DataFrame(coleccion.find({"$and": [cond1, cond2]},{"name": 1, "_id": 0, "number_of_employees":1}).sort({"number_of_employees":1}))
Name_number.head(2)

       name  number_of_employees
0  TrialPay                  100
1     InteQ                  100

### 9. Ordena todas las empresas por su precio de IPO en orden descendente.

In [223]:
Ipo =pd.DataFrame(coleccion.find().sort({'ipo.valuation_amount':-1}))
Ipo.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7e4bab8bd67529a8b4,GREE,gree,http://www.crunchbase.com/company/gree,http://www.gree-corp.com,,,gree_corp,games_video,700.0,2004.0,12.0,7.0,NaN,NaN,NaN,None,"mobile-web, japan, tokyo, social-network, mobi...",None,inquiry@gree-corp.com,,"Internet media business,SNS, free game",Sat Dec 20 16:42:57 UTC 2008,Tue Jan 01 21:37:04 UTC 2013,<p>GREE provides Japan&#8217;s leading mobile ...,"{'available_sizes': [[[150, 61], 'assets/image...",[],"[{'is_past': False, 'title': 'CEO', 'person': ...","[{'competitor': {'name': 'Mobage-town', 'perma...",[],¥464M,"[{'id': 18872, 'round_code': 'unattributed', '...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': 104000000, 'price_currency_c...","[{'description': 'Headquarters', 'address1': '...","[{'id': 1021, 'description': 'IPO', 'stoned_ye...","{'valuation_amount': 108960000000, 'valuation_...",[],"[{'available_sizes': [[[133, 150], 'assets/ima...",[],[]
1,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,2.0,1.0,NaN,NaN,NaN,,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,Thu Nov 21 19:40:55 UTC 2013,<p>Facebook is the world&#8217;s largest socia...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Facebook Platform', 'permalink': 'f...","[{'is_past': False, 'title': 'Founder and CEO,...","[{'competitor': {'name': 'MySpace', 'permalink...","[{'title': '', 'is_past': False, 'provider': {...",$2.43B,"[{'id': 2, 'round_code': 'angel', 'source_url'...","[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]

In [222]:
#Ipo['valuation amount'] = Ipo['ipo'].apply(lambda x: x['valuation_amount'])

TypeError: 'NoneType' object is not subscriptable


### 10. Recupera las 10 empresas con más empleados, ordenadas por el `número de empleados`.

In [181]:
mas_emple = pd.DataFrame(coleccion.find().sort('number_of_employees', -1).limit(10))
mas_emple.head()

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd67529941a,Siemens,siemens,http://www.crunchbase.com/company/siemens,http://www.siemens.com,,,Siemens,hardware,405000,1847,NaN,NaN,None,None,None,None,"automation, building-technologies, drive-techn...",,contact@siemens.com,49 89 636 34134,Electronics and Electrical Engineering,Thu Jul 31 09:29:43 UTC 2008,Thu Nov 28 20:32:55 UTC 2013,"<p>Siemens AG, an electronics and electrical e...","{'available_sizes': [[[150, 34], 'assets/image...",[],"[{'is_past': False, 'title': 'Chairman, Superv...",[],"[{'title': 'Application Development', 'is_past...",$8.9M,"[{'id': 17062, 'round_code': 'grant', 'source_...",[],None,"[{'price_amount': 418000000, 'price_currency_c...","[{'description': '', 'address1': 'Wittelsbache...","[{'id': 35852, 'description': 'Siemens Receive...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<iframe width=""420"" height=""3...","[{'available_sizes': [[[150, 92], 'assets/imag...",[],[]
1,52cdef7c4bab8bd67529856a,IBM,ibm,http://www.crunchbase.com/company/ibm,http://www.ibm.com,,,IBM,software,388000,1896,NaN,NaN,None,None,None,,,,ews@us.ibm.com,914-499-1900,,Fri Mar 14 22:55:52 UTC 2008,Sat Jan 04 02:56:24 UTC 2014,"<p>IBM, acronym for International Business Mac...","{'available_sizes': [[[150, 60], 'assets/image...","[{'name': 'Lotus Notes', 'permalink': 'lotus-n...","[{'is_past': False, 'title': 'Chairman of the ...","[{'competitor': {'name': 'BEA Systems', 'perma...","[{'title': '', 'is_past': False, 'provider': {...",$0,[],"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 10471, 'description': 'IBM Completes A...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...","[{'external_url': 'http://mashpedia.com/IBM', ...",[]
2,52cdef7d4bab8bd675299d33,Toyota,toyota,http://www.crunchbase.com/company/toyota,http://www.toyota-global.com,,,Toyota,enterprise,320000,1933,NaN,NaN,None,None,None,None,None,,,81 5 6528 2121,Automotive,Mon Sep 22 22:00:26 UTC 2008,Mon Nov 11 16:24:21 UTC 2013,<p>Toyota operates 75 manufacturing companies ...,"{'available_sizes': [[[135, 37], 'assets/image...",[],"[{'is_past': False, 'title': '', 'person': {'f...",[],"[{'title': '', 'is_past': True, 'provider': {'...",$0,[],"[{'funding_round': {'round_code': 'a', 'source...",None,[],"[{'description': 'HQ', 'address1': 'Toyota Mot...",[],None,"[{'embed_code': '<iframe width=""430"" height=""3...","[{'available_sizes': [[[150, 84], 'assets/imag...",[],[]
3,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000,1998,12.0,1.0,None,None,None,None,"moneytransfer, crunchbase, ecommerce, paypal, ...",,,207-619-2873,Internet payment service,Wed Aug 01 09:16:46 UTC 2007,Fri Dec 20 04:43:53 UTC 2013,<p>PayPal is an online payments and money tran...,"{'available_sizes': [[[150, 51], 'assets/image...","[{'name': 'PayPal Here', 'permalink': 'paypal-...","[{'is_past': False, 'title': 'Vice President, ...","[{'competitor': {'name': 'KushCash', 'permalin...","[{'title': 'Public Relations', 'is_past': True...",$197M,"[{'id': 284, 'round_code': 'd', 'source_url': ...","[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]
4,52cdef7e4bab8bd67529b0fe,Nippon Telegraph and Telephone Corporation,nippon-telegraph-and-telephone-corporation,http://www.crunchbase.com/company/nippon-teleg...,http://www.ntt.co.jp/index_e.html,,,,None,227000,1985,4.0,1.0,None,None,None,None,None,,,,,Tue Feb 17 16:43:28 UTC 2009,Mon Dec 23 19:36:20 UTC 2013,<p>In the information and communication techno...,"{'available_sizes': [[[150, 34], 'assets/image...",[],"[{'is_past': True, 'title': 'System consultant...",[],[],$0,[],"[{'funding_round': {'round_code': 'e', 'source...",None,[],"[{'description': 'NTT', 'address1': '3-1, Otem...",[],None,[],"[{'available_sizes': [[[150, 42], 'assets/imag...",[],[]

### 11. Todas las empresas fundadas en el segundo semestre del año. Limita tu búsqueda a 1000 empresas.

In [184]:
segundo_semestre = pd.DataFrame(coleccion.find({"founded_month": {"$gte": 7, "$lte": 12}}).limit(1000))
segundo_semestre.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,video_embeds,screenshots,external_links,partners,deadpooled_month,deadpooled_day,deadpooled_url,ipo
0,52cdef7c4bab8bd675297d8a,Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,2005,10,17.0,1.0,"wiki, seattle, elowitz, media-industry, media-...",,info@wetpaint.com,206.859.6300,Technology Platform Company,2007-05-25 06:51:27,Sun Dec 08 07:15:44 UTC 2013,<p>Wetpaint is a technology platform company t...,"{'available_sizes': [[[150, 75], 'assets/image...","[{'name': 'Wikison Wetpaint', 'permalink': 'we...","[{'is_past': False, 'title': 'Co-Founder and V...","[{'competitor': {'name': 'Wikia', 'permalink':...",[],$39.8M,"[{'id': 888, 'round_code': 'a', 'source_url': ...",[],"{'price_amount': 30000000, 'price_currency_cod...",[],"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],NaN,NaN,NaN,NaN
1,52cdef7c4bab8bd675297d8c,Zoho,abc4,http://www.crunchbase.com/company/zoho,http://zoho.com,http://blogs.zoho.com/,http://blogs.zoho.com/feed,zoho,software,1600.0,2005,9,15.0,3.0,"zoho, officesuite, spreadsheet, writer, projec...",,info@zohocorp.com,1-888-204-3539,Online Business Apps Suite,Fri May 25 19:30:28 UTC 2007,Wed Oct 30 00:07:05 UTC 2013,"<p>Zoho offers a suite of Business, Collaborat...","{'available_sizes': [[[150, 55], 'assets/image...","[{'name': 'Zoho Office Suite', 'permalink': 'z...","[{'is_past': False, 'title': 'CEO and Founder'...","[{'competitor': {'name': 'Empressr', 'permalin...",[],$0,[],[],None,[],"[{'description': 'Headquarters', 'address1': '...","[{'id': 388, 'description': 'Zoho Reaches 2 Mi...","[{'embed_code': '<object width=""430"" height=""2...",[],[{'external_url': 'http://www.online-tech-tips...,[],NaN,NaN,NaN,NaN


### 12. Todas las empresas fundadas antes del año 2000 que tienen un monto de adquisición superior a 10.000.000.

In [193]:
d_adquiridas = pd.DataFrame(coleccion.find({"founded_year": {"$lt": 2000},"acquisition.price_amount": {"$gt": 10000000}}))
d_adquiridas.head(2)

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,founded_month,founded_day,deadpooled_year,deadpooled_month,deadpooled_day,deadpooled_url,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,image,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297d90,Postini,postini,http://www.crunchbase.com/company/postini,http://postini.com,,,None,web,NaN,1999,6.0,2.0,NaN,NaN,NaN,None,,None,,888.584.3150,None,Fri Jun 08 12:19:51 UTC 2007,Sat Aug 13 18:02:34 UTC 2011,<p>Postini focuses on two main issues: securit...,"{'available_sizes': [[[150, 61], 'assets/image...","[{'name': 'Postini Solutions', 'permalink': 'p...","[{'is_past': False, 'title': 'Board', 'person'...","[{'competitor': {'name': 'RescueTime', 'permal...",[],$0,[],[],"{'price_amount': 625000000, 'price_currency_co...",[],"[{'description': None, 'address1': '959 Skyway...",[],None,[],[],[],[]
1,52cdef7c4bab8bd675297deb,SideStep,sidestep,http://www.crunchbase.com/company/sidestep,http://www.sidestep.com,None,None,None,web,75.0,1999,11.0,1.0,NaN,NaN,NaN,None,"deals, travel, flights, hotels, tickets, vacat...",None,None,408-235-1700,None,Wed Jul 11 02:50:10 UTC 2007,Thu Jan 13 02:41:17 UTC 2011,<p>SideStep is a metasearch engine for travel ...,"{'available_sizes': [[[150, 52], 'assets/image...","[{'name': 'SideStep', 'permalink': 'sidestep'}]","[{'is_past': False, 'title': 'Board', 'person'...","[{'competitor': {'name': 'Mobissimo', 'permali...",[],$32M,"[{'id': 105, 'round_code': 'c', 'source_url': ...",[],"{'price_amount': 180000000, 'price_currency_co...",[],"[{'description': None, 'address1': '2980 Bower...",[],None,[],[],[],[]


### 13. Todas las empresas que han sido adquiridas después de 2010, ordénalas por el monto de adquisición, y recupera solo los campos `name` y `acquisition`.

In [192]:
Ordenadas_foun_year =  pd.DataFrame(coleccion.find({"acquisition.acquired_year": {"$gt": 2010}},{"name": 1, "acquisition": 1, "_id": 0}).sort("acquisition.price_amount", -1))

### 14. Ordena las empresas por su `founded year`, recuperando solo los campos `name` y `founded year`.

In [197]:
ordenado_año = pd.DataFrame(coleccion.find({}, {'name': 1, 'founded_year': 1, '_id': 0}).sort('founded_year', -1))
ordenado_año.head(10)

        name  founded_year
0     Clowdy        2013.0
1       Pikk        2013.0
2   WhosCall        2013.0
3     iBazar        2013.0
4     Gimigo        2013.0
5   SEOGroup        2013.0
6   Shopseen        2013.0
7    Tongxue        2013.0
8  Advaliant        2013.0
9       Fluc        2013.0


### 15. Todas las empresas que han sido fundadas en los primeros siete días del mes, incluyendo el séptimo. Ordénalas por su `acquisition price` en orden descendente. Limita la búsqueda a 10 documentos.

In [199]:
precio_ad_order = pd.DataFrame(coleccion.find({'founded_day': {'$lte': 7}}, {'name': 1, 'acquisition': 1, '_id': 0}).sort('acquisition.price_amount', -1).limit(10))
precio_ad_order             # no se ordena puesto que habria que entrar dentro de acquisition...

                name                                        acquisition
0           Netscape  {'price_amount': 4200000000, 'price_currency_c...
1             PayPal  {'price_amount': 1500000000, 'price_currency_c...
2             Zappos  {'price_amount': 1200000000, 'price_currency_c...
3            Alibaba  {'price_amount': 1000000000, 'price_currency_c...
4            Postini  {'price_amount': 625000000, 'price_currency_co...
5             Danger  {'price_amount': 500000000, 'price_currency_co...
6  Clearwell Systems  {'price_amount': 410000000, 'price_currency_co...
7         PrimeSense  {'price_amount': 345000000, 'price_currency_co...
8             Amobee  {'price_amount': 321000000, 'price_currency_co...
9        BlueLithium  {'price_amount': 300000000, 'price_currency_co...

### 16. Todas las empresas en la categoría 'web' que tienen más de 4000 empleados. Ordénalas por la cantidad de empleados en orden ascendente.

In [201]:
web = pd.DataFrame(coleccion.find({'category_code': 'web', 'number_of_employees': {'$gt': 4000}}, 
                                  {'name': 1, 'number_of_employees': 1, '_id': 0}).sort('number_of_employees', 1))
web

                            name  number_of_employees
0                        Expedia                 4400
1                            AOL                 8000
2                        Webkinz                 8657
3                        Rakuten                10000
4  Los Angeles Times Media Group                10000
5                        Groupon                10000
6                         Yahoo!                13600
7                           eBay                15000
8                       Experian                15500

### 17. Todas las empresas cuyo monto de adquisición es superior a 10.000.000, y cuya moneda es 'EUR'.

In [204]:
empresas_monto = pd.DataFrame(coleccion.find({'acquisition.price_amount': {'$gt': 10000000}, 
                                              'acquisition.price_currency_code': 'EUR'}, 
                                              {'name': 1, 'acquisition': 1, '_id': 0}))

In [206]:
empresas_monto.head() # igual no irdena acquisition

                name                                        acquisition
0                ZYB  {'price_amount': 31500000, 'price_currency_cod...
1            Apertio  {'price_amount': 140000000, 'price_currency_co...
2  Greenfield Online  {'price_amount': 40000000, 'price_currency_cod...
3            Webedia  {'price_amount': 70000000, 'price_currency_cod...
4          Wayfinder  {'price_amount': 24000000, 'price_currency_cod...

### 18. Todas las empresas que han sido adquiridas en el primer trimestre del año. Limita la búsqueda a 10 empresas, y recupera solo los campos `name` y `acquisition`.

In [207]:
primer_trimestre= pd.DataFrame(coleccion.find({'acquisition.acquired_month': {'$lte': 3}}, {'name': 1, 'acquisition': 1, '_id': 0}).limit(10))

In [208]:
primer_trimestre

          name                                        acquisition
0         Kyte  {'price_amount': None, 'price_currency_code': ...
1   NetRatings  {'price_amount': 327000000, 'price_currency_co...
2       blogTV  {'price_amount': None, 'price_currency_code': ...
3   Livestream  {'price_amount': None, 'price_currency_code': ...
4     iContact  {'price_amount': 169000000, 'price_currency_co...
5      Coghead  {'price_amount': None, 'price_currency_code': ...
6  Dailymotion  {'price_amount': 168000000, 'price_currency_co...
7     Netvibes  {'price_amount': None, 'price_currency_code': ...
8       Flickr  {'price_amount': None, 'price_currency_code': ...
9   BabyCenter  {'price_amount': None, 'price_currency_code': ...

In [215]:
primer_trimestre['price_amount'] = primer_trimestre['acquisition'].apply(lambda x: x['price_amount'])

#accedo al elemeneto dentro del elemento acqusition del data frame anterior aplico una landa donde x : es xde ese valir de la key anterior

In [220]:
df_sorted = primer_trimestre.sort_values(by='price_amount', ascending=False)

In [221]:
df_sorted.drop(columns='acquisition')

          name  price_amount
1   NetRatings   327000000.0
4     iContact   169000000.0
6  Dailymotion   168000000.0
0         Kyte           NaN
2       blogTV           NaN
3   Livestream           NaN
5      Coghead           NaN
7     Netvibes           NaN
8       Flickr           NaN
9   BabyCenter           NaN